repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: debug-statements
    -   id: fix-byte-order-marker
    -   id: end-of-file-fixer
        exclude: 'static'
    -   id: fix-encoding-pragma
        args: ['--remove']
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ['--fix=lf']

-   repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
