version: '3.9'

services:
  web:
    image: gfw-gmail-catcher
    container_name: gfw-gmail-catcher
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHON_ENV=dev
      - WRITE_PATH=/srv/src/data/
    volumes:
      - c:/Users/fredi/Desktop/ArcGIS/GLAD_Alerts:/srv/src/data
